name: bardensr_bsp
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - arrow-cpp
  - h5py
  - imageio
  - ipython
  - joblib
  - jupyter
  - keras
  - matplotlib
  - natsort
  - networkx
  - numpy==1.26.4
  - pandas
  - pip
  - pip:
    - git+https://github.com/jacksonloper/bardensr.git
  - pyarrow
  - python
  - scikit-image
  - scipy
  - tensorflow